FROM postgres:14.2-alpine

ENV POSTGRES_USER app_user
ENV POSTGRES_PASSWORD app_passw@rd
ENV POSTGRES_DB serasa_ms

COPY .docker/postgres/init.sh /docker-entrypoint-initdb.d

VOLUME /var/lib/postgresql/data
EXPOSE 5432
