FROM openjdk:18-alpine

RUN apk update && apk add --no-cache tzdata fontconfig freetype-dev expat ttf-dejavu libpng libjpeg-turbo msttcorefonts-installer

RUN mkdir /app

COPY ms-launcher/target/*.jar /app/

ARG ADDITIONAL_OPTS

ENV ADDITIONAL_OPTS=${ADDITIONAL_OPTS}

SHELL ["/bin/sh", "-c"]

EXPOSE 8080

EXPOSE 5005

WORKDIR /app

ENV WAIT_VERSION 2.7.2
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/$WAIT_VERSION/wait /wait
RUN chmod +x /wait

CMD java ${ADDITIONAL_OPTS} -jar ms-launcher-*.jar
